### ISSUE TITLE
Kafka exceptions currently crash the process

### ISSUE THREAD

**Issue by rtyler** [lookout/verspaetung#23]
This might get resolved with #20 and some of the refactoring introduced in it

```
kafka.common.NotLeaderForPartitionException: null                                                              [0/1869]
        at sun.reflect.GeneratedConstructorAccessor320.newInstance(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526) ~[na:1.7.0_71]
        at java.lang.Class.newInstance(Class.java:379) ~[na:1.7.0_71]
        at kafka.common.ErrorMapping$.exceptionFor(ErrorMapping.scala:73) ~[verspaetung-0.1.5-all.jar:na]
        at kafka.consumer.SimpleConsumer.earliestOrLatestOffset(SimpleConsumer.scala:160) ~[verspaetung-0.1.5-all.jar:n
        at sun.reflect.GeneratedMethodAccessor14.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_71]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_71]
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoCachedMethodSiteNoUnwrap.invoke(PojoMetaMethodSi
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53) [verspaetung-0.1.5-
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:136) [verspaetung-0.1.5-all
        at com.github.lookout.verspaetung.KafkaPoller.latestFromLeader(KafkaPoller.groovy:118) [verspaetung-0.1.5-all.j
        at com.github.lookout.verspaetung.KafkaPoller$latestFromLeader$4.callCurrent(Unknown Source) ~[na:na]
        at com.github.lookout.verspaetung.KafkaPoller.processDeltasFor(KafkaPoller.groovy:102) [verspaetung-0.1.5-all.j
        at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_71]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_71]
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90) ~[verspaetung-0.1.5-all.jar:na]
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324) ~[verspaetung-0.1.5-all.jar:na]
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:382) ~[verspaetung
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1017) [verspaetung-0.1.5-all.jar:na]
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:66) [verspaetung-0
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:169) [verspaetung-0.
        at com.github.lookout.verspaetung.KafkaPoller$_dumpMetadata_closure1.doCall(KafkaPoller.groovy:67) ~[verspaetun
        at sun.reflect.GeneratedMethodAccessor12.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_71]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_71]
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90) ~[verspaetung-0.1.5-all.jar:na]
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324) ~[verspaetung-0.1.5-all.jar:na]
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:292) ~[verspaetung
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1017) [verspaetung-0.1.5-all.jar:na]
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:39) [verspaetung-0.1.5-al
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:128) [verspaetung-0.1.5-all
        at com.github.lookout.verspaetung.KafkaPoller$_withTopicsAndPartitions_closure2$_closure8.doCall(KafkaPoller.gr
        at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_71]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_71]
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90) ~[verspaetung-0.1.5-all.jar:na]
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324) ~[verspaetung-0.1.5-all.jar:na]
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:292) ~[verspaetung
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1017) [verspaetung-0.1.5-all.jar:na]
        at groovy.lang.Closure.call(Closure.java:423) [verspaetung-0.1.5-all.jar:na]
        at groovy.lang.Closure.call(Closure.java:439) [verspaetung-0.1.5-all.jar:na]
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2027) [verspaetung-0.1.5-all
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2012) [verspaetung-0.1.5-all
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2041) [verspaetung-0.1.5-all
        at org.codehaus.groovy.runtime.dgm$160.invoke(Unknown Source) [verspaetung-0.1.5-all.jar:na]
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMe
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53) [verspaetung-0.1.5-
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120) [verspaetung-0.1.5-all
        at com.github.lookout.verspaetung.KafkaPoller$_withTopicsAndPartitions_closure2.doCall(KafkaPoller.groovy:86) [
        at sun.reflect.GeneratedMethodAccessor15.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_71]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_71]
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90) ~[verspaetung-0.1.5-all.jar:na]
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324) ~[verspaetung-0.1.5-all.jar:na]
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:292) ~[verspaetung
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1017) [verspaetung-0.1.5-all.jar:na]
        at groovy.lang.Closure.call(Closure.java:423) [verspaetung-0.1.5-all.jar:na]
        at groovy.lang.Closure.call(Closure.java:439) [verspaetung-0.1.5-all.jar:na]
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2027) [verspaetung-0.1.5-all
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2012) [verspaetung-0.1.5-all
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2041) [verspaetung-0.1.5-all
        at org.codehaus.groovy.runtime.dgm$160.invoke(Unknown Source) [verspaetung-0.1.5-all.jar:na]
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMe
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53) [verspaetung-0.1.5-
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120) [verspaetung-0.1.5-all
        at com.github.lookout.verspaetung.KafkaPoller.withTopicsAndPartitions(KafkaPoller.groovy:85) [verspaetung-0.1.5
        at com.github.lookout.verspaetung.KafkaPoller$withTopicsAndPartitions$2.callCurrent(Unknown Source) [verspaetun
        at com.github.lookout.verspaetung.KafkaPoller.dumpMetadata(KafkaPoller.groovy:65) [verspaetung-0.1.5-all.jar:na
        at com.github.lookout.verspaetung.KafkaPoller$dumpMetadata$1.callCurrent(Unknown Source) [verspaetung-0.1.5-all
        at com.github.lookout.verspaetung.KafkaPoller.run(KafkaPoller.groovy:53) [verspaetung-0.1.5-all.jar:na]

```

**Comment by rtyler** [comment]
With the refactoring of KafkaPoller in #20 this specific exception was addressed. Fetching latest offsets from the leader is now exception gaurded. There's a possibility for another Kafa-related exception to break us in `fetchMetadataForCurrentTopics` which needs to be gaurded still.
